name: main

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true
    
    - name: commit 
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: update hosts
      run: |
        python update.py
    
    - name: push
      run: |
        echo "======================="
        git add . && git commit -m "$(date "+%Y%m%d-%H%M")" && git push && echo "UPDATE SUCCESS!" || echo "There are currently no updates!"
        echo "======================="
        

